/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Lumina Glass Design System — AI Graduation Portrait Studio
        background: '#131315',
        surface: '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1b1b1d',
        'surface-container': '#1f1f21',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'surface-variant': '#353437',
        'on-surface': '#e4e2e4',
        'on-surface-variant': '#c1c6d7',
        'inverse-on-surface': '#303032',
        'inverse-surface': '#e4e2e4',
        outline: '#8b90a0',
        'outline-variant': '#414755',
        primary: '#adc6ff',
        'on-primary': '#002e69',
        'primary-container': '#4b8eff',
        'on-primary-container': '#00285c',
        'inverse-primary': '#005bc1',
        secondary: '#e8b3ff',
        'on-secondary': '#510074',
        'secondary-container': '#7508a5',
        'on-secondary-container': '#e19fff',
        tertiary: '#ffb595',
        'on-tertiary': '#571e00',
        'tertiary-container': '#ef6719',
        'on-tertiary-container': '#4c1a00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'surface-tint': '#adc6ff',
        'pop-yellow': '#FFD700',
        'pop-red': '#FF003C',
        'pop-blue': '#00E5FF',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Inter'],
        label: ['Inter'],
        'pop-display': ['Impact', 'sans-serif-condensed'],
        'pop-body': ['Arial Rounded MT Bold', 'System'],
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      spacing: {
        'margin-main': '20px',
        gutter: '12px',
        'stack-gap': '16px',
        'glass-padding': '20px',
      },
    },
  },
  plugins: [],
};
